export const MOBILE_BREAKPOINT = 900
export const CHARACTER_INTERMEDIATE_MAX_WIDTH = 1150
export const CHARACTER_MOBILE_PORTRAIT_INTERMEDIATE_MIN_WIDTH = 700
export const CHARACTER_MOBILE_INTERMEDIATE_MIN_WIDTH = 800
