import type { OseImportMonsterRecord } from './oseMonsterTypes'

export const OSE_NORMALIZED_MONSTERS: OseImportMonsterRecord[] = [
  {
    id: 'ose-monster-basilisk',
    rulesetId: 'ose',
    name: 'Basilisk',
    shortDescription: "10' long, serpentine lizards. Unintelligent, but highly magical. Dwell in caverns and twisted brambles.",
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-basilisk-bite',
        count: '1',
        attackClass: 'melee',
        attackType: 'bite',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd10',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [
          {
            id: 'ose-monster-basilisk-bite-petrify',
            effectClass: 'save',
            effectType: 'paralysis_petrification',
            customType: '',
            notes: 'Save vs petrify or turned to stone.',
          },
        ],
        notes: 'Petrifying touch on bite.',
      },
      {
        id: 'ose-monster-basilisk-gaze',
        count: '1',
        attackClass: 'special',
        attackType: 'gaze',
        customAttackType: '',
        damageDiceCount: '',
        damageDie: '',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [
          {
            id: 'ose-monster-basilisk-gaze-petrify',
            effectClass: 'save',
            effectType: 'paralysis_petrification',
            customType: '',
            notes: "Save vs petrify or turned to stone when meeting the basilisk's gaze.",
          },
        ],
        notes: 'Effect-only gaze attack; no damage roll.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-basilisk-surprise',
        name: 'Surprise',
        trigger: '',
        saveType: '',
        effect: "Characters surprised by a basilisk meet its gaze.",
      },
      {
        id: 'ose-monster-basilisk-petrifying-touch',
        name: 'Petrifying touch',
        trigger: '',
        saveType: 'paralysis_petrification',
        effect: 'Anyone touched by a basilisk is turned to stone.',
      },
      {
        id: 'ose-monster-basilisk-petrifying-gaze',
        name: 'Petrifying gaze',
        trigger: '',
        saveType: 'paralysis_petrification',
        effect: "Anyone meeting a basilisk's gaze is turned to stone. Unless averting eyes or using a mirror, characters in melee are affected each round.",
      },
      {
        id: 'ose-monster-basilisk-averting-eyes',
        name: 'Averting eyes',
        trigger: '',
        saveType: '',
        effect: 'Characters fighting with averted eyes take a -4 penalty to hit; the basilisk gains +2 to attack.',
      },
      {
        id: 'ose-monster-basilisk-mirrors',
        name: 'Mirrors',
        trigger: '',
        saveType: '',
        effect: 'The reflection of a basilisk is harmless. Fighting by looking in a mirror incurs a -1 penalty to attack. If a basilisk sees its own reflection (2-in-6 chance), it must save or be petrified.',
      },
    ],
    notes: '',
    stats: {
      ac: '4',
      thac0: '13',
      hd_dice: '6',
      hd_mod: '1',

      mv_land: '60',
      sv_d: '10',
      sv_w: '11',
      sv_p: '12',
      sv_b: '13',
      sv_s: '14',
      ml: '9',
      al: 'Neutral',
      xp: '950',
      na_dungeon_count: '1',
      na_dungeon_die: 'd6',
      na_wilderness_count: '1',
      na_wilderness_die: 'd6',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-basilisk-tt-f',
        code: 'F',
        treasureTableId: 'ose-tt-f',
        notes: '',
      },
    ],
  },
  {
    id: 'ose-monster-bandit',
    rulesetId: 'ose',
    name: 'Bandit',
    shortDescription: 'NPC thieves who live by robbery.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-bandit-weapon',
        count: '1',
        attackClass: 'melee',
        attackType: 'weapon',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd6',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: '1d6 or by weapon.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-bandit-trickery',
        name: 'Trickery',
        trigger: '',
        saveType: '',
        effect: 'Use disguise or trickery to surprise victims.',
      },
      {
        id: 'ose-monster-bandit-leader',
        name: 'Leader',
        trigger: '',
        saveType: '',
        effect: 'May have a leader of 2nd level or higher (any human class).',
      },
    ],
    notes: '',
    stats: {
      ac: '6',
      thac0: '19',
      hd_dice: '1',
      hd_mod: '0',

      mv_land: '120',
      sv_d: '13',
      sv_w: '14',
      sv_p: '13',
      sv_b: '16',
      sv_s: '15',
      ml: '8',
      al: 'Neutral or Chaotic',
      xp: '10',
      na_dungeon_count: '1',
      na_dungeon_die: 'd8',
      na_wilderness_count: '3',
      na_wilderness_die: 'd10',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-bandit-tt-u',
        code: 'U',
        treasureTableId: 'ose-tt-u',
        notes: 'Standard treasure carried by encountered bandits.',
      },
      {
        id: 'ose-monster-bandit-tt-a',
        code: 'A',
        treasureTableId: 'ose-tt-a',
        notes: 'Only when encountered in their wilderness lair.',
      },
    ],
  },
  {
    id: 'ose-monster-ape-white',
    rulesetId: 'ose',
    name: 'Ape, White',
    shortDescription: 'Albino, herbivorous, gorilla-like apes that live in caves and emerge at night to forage.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-ape-white-claw',
        count: '2',
        attackClass: 'melee',
        attackType: 'claw',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd4',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: '',
      },
      {
        id: 'ose-monster-ape-white-thrown-rock',
        count: '1',
        attackClass: 'missile',
        attackType: 'thrown',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd6',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: 'Thrown rock.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-ape-white-territorial',
        name: 'Territorial',
        trigger: '',
        saveType: '',
        effect: 'Defend their lair with threats and, if this is ignored, violence.',
      },
    ],
    notes: '',
    stats: {
      ac: '6',
      thac0: '16',
      hd_dice: '4',
      hd_mod: '0',

      mv_land: '120',
      sv_d: '12',
      sv_w: '13',
      sv_p: '14',
      sv_b: '15',
      sv_s: '16',
      ml: '7',
      al: 'Neutral',
      xp: '75',
      na_dungeon_count: '1',
      na_dungeon_die: 'd6',
      na_wilderness_count: '2',
      na_wilderness_die: 'd4',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-ape-white-tt-none',
        code: 'None',
        treasureTableId: null,
        notes: '',
      },
    ],
  },
  {
    id: 'ose-monster-goblin',
    rulesetId: 'ose',
    name: 'Goblin',
    shortDescription: 'Small, grotesque humanoids with pallid, earth-coloured skin and glowing, red eyes. Dwell underground.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-goblin-weapon',
        count: '1',
        attackClass: 'melee',
        attackType: 'weapon',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd6',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: '1d6 or by weapon.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-goblin-infravision',
        name: 'Infravision',
        trigger: '',
        saveType: '',
        effect: "90' infravision.",
      },
      {
        id: 'ose-monster-goblin-hate-sun',
        name: 'Hate the sun',
        trigger: '',
        saveType: '',
        effect: '-1 to-hit in full daylight.',
      },
      {
        id: 'ose-monster-goblin-wolf-riders',
        name: 'Wolf riders',
        trigger: '',
        saveType: '',
        effect: '20% of goblin groups encountered have wolf riders: ¼ of the group mounted on dire wolves.',
      },
      {
        id: 'ose-monster-goblin-hate-dwarves',
        name: 'Hate dwarves',
        trigger: '',
        saveType: '',
        effect: 'Attack dwarves on sight.',
      },
      {
        id: 'ose-monster-goblin-king',
        name: 'Goblin king and bodyguards',
        trigger: '',
        saveType: '',
        effect: 'A 3HD (15hp) king and 2d6 2HD bodyguards live in the goblin lair. They do not suffer attack penalties in daylight. The king gains a +1 bonus to damage. Morale is 9 when the king is present.',
      },
    ],
    notes: '',
    stats: {
      ac: '6',
      thac0: '19',
      hd_dice: '1',
      hd_mod: '-1',

      mv_land: '60',
      sv_d: '14',
      sv_w: '15',
      sv_p: '16',
      sv_b: '17',
      sv_s: '18',
      ml: '7',
      al: 'Chaotic',
      xp: '5',
      na_dungeon_count: '2',
      na_dungeon_die: 'd4',
      na_wilderness_count: '6',
      na_wilderness_die: 'd10',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-goblin-tt-r',
        code: 'R',
        treasureTableId: 'ose-tt-r',
        notes: '',
      },
      {
        id: 'ose-monster-goblin-tt-c',
        code: 'C',
        treasureTableId: 'ose-tt-c',
        notes: 'Only in wilderness or lair.',
      },
    ],
  },
  {
    id: 'ose-monster-goblin-king',
    rulesetId: 'ose',
    name: 'Goblin King',
    shortDescription: 'Leader of a goblin lair. Does not suffer attack penalties in daylight.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-goblin-king-weapon',
        count: '1',
        attackClass: 'melee',
        attackType: 'weapon',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd6',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: '1d6 or by weapon, +1 damage bonus.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-goblin-king-infravision',
        name: 'Infravision',
        trigger: '',
        saveType: '',
        effect: "90' infravision.",
      },
      {
        id: 'ose-monster-goblin-king-no-sun-penalty',
        name: 'No sun penalty',
        trigger: '',
        saveType: '',
        effect: 'Does not suffer the -1 to-hit penalty in daylight that regular goblins do.',
      },
      {
        id: 'ose-monster-goblin-king-hate-dwarves',
        name: 'Hate dwarves',
        trigger: '',
        saveType: '',
        effect: 'Attack dwarves on sight.',
      },
      {
        id: 'ose-monster-goblin-king-morale-boost',
        name: 'Morale boost',
        trigger: '',
        saveType: '',
        effect: 'All goblins have morale 9 when the king is present.',
      },
    ],
    notes: '',
    stats: {
      ac: '6',
      thac0: '19',
      hd_dice: '3',
      hd_mod: '0',

      mv_land: '60',
      sv_d: '14',
      sv_w: '15',
      sv_p: '16',
      sv_b: '17',
      sv_s: '18',
      ml: '9',
      al: 'Chaotic',
      xp: '35',
      na_dungeon_count: '1',
      na_dungeon_die: 'd1',
      na_wilderness_count: '1',
      na_wilderness_die: 'd1',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-goblin-king-tt-r',
        code: 'R',
        treasureTableId: 'ose-tt-r',
        notes: '',
      },
      {
        id: 'ose-monster-goblin-king-tt-c',
        code: 'C',
        treasureTableId: 'ose-tt-c',
        notes: 'Only in wilderness or lair.',
      },
    ],
  },
  {
    id: 'ose-monster-goblin-bodyguard',
    rulesetId: 'ose',
    name: 'Goblin Bodyguard',
    shortDescription: 'Elite goblin guards that protect the goblin king. Do not suffer attack penalties in daylight.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-goblin-bodyguard-weapon',
        count: '1',
        attackClass: 'melee',
        attackType: 'weapon',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd6',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [],
        notes: '1d6 or by weapon.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-goblin-bodyguard-infravision',
        name: 'Infravision',
        trigger: '',
        saveType: '',
        effect: "90' infravision.",
      },
      {
        id: 'ose-monster-goblin-bodyguard-no-sun-penalty',
        name: 'No sun penalty',
        trigger: '',
        saveType: '',
        effect: 'Does not suffer the -1 to-hit penalty in daylight that regular goblins do.',
      },
      {
        id: 'ose-monster-goblin-bodyguard-hate-dwarves',
        name: 'Hate dwarves',
        trigger: '',
        saveType: '',
        effect: 'Attack dwarves on sight.',
      },
    ],
    notes: '',
    stats: {
      ac: '6',
      thac0: '19',
      hd_dice: '2',
      hd_mod: '0',

      mv_land: '60',
      sv_d: '14',
      sv_w: '15',
      sv_p: '16',
      sv_b: '17',
      sv_s: '18',
      ml: '9',
      al: 'Chaotic',
      xp: '20',
      na_dungeon_count: '2',
      na_dungeon_die: 'd6',
      na_wilderness_count: '2',
      na_wilderness_die: 'd6',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-goblin-bodyguard-tt-r',
        code: 'R',
        treasureTableId: 'ose-tt-r',
        notes: '',
      },
      {
        id: 'ose-monster-goblin-bodyguard-tt-c',
        code: 'C',
        treasureTableId: 'ose-tt-c',
        notes: 'Only in wilderness or lair.',
      },
    ],
  },
  {
    id: 'ose-monster-dryad',
    rulesetId: 'ose',
    name: 'Dryad',
    shortDescription: 'Shy, peaceful, yet wary tree spirits that can manifest as beautiful female humanoids. Live in deep forests.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-dryad-charm',
        count: '1',
        attackClass: 'spell',
        attackType: 'spell_like',
        customAttackType: '',
        damageDiceCount: '',
        damageDie: '',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [
          {
            id: 'ose-monster-dryad-charm-effect',
            effectClass: 'save',
            effectType: 'spells',
            customType: '',
            notes: 'Save vs spells at -2. Victim compelled to approach the tree, vanishes inside it. If not immediately rescued, the victim is lost forever.',
          },
        ],
        notes: 'Charm. No damage.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-dryad-bound-with-tree',
        name: 'Bound with tree',
        trigger: '',
        saveType: '',
        effect: "Spiritually connected with a single tree. Dryad dies if the tree dies, or if separated by more than 240'.",
      },
      {
        id: 'ose-monster-dryad-meld-with-tree',
        name: 'Meld with tree',
        trigger: '',
        saveType: '',
        effect: 'Can disappear by joining with her tree.',
      },
      {
        id: 'ose-monster-dryad-defensive',
        name: 'Defensive',
        trigger: '',
        saveType: '',
        effect: 'Distrustful of strangers. Attempt to charm anyone who approaches or follows.',
      },
      {
        id: 'ose-monster-dryad-treasure',
        name: 'Treasure',
        trigger: '',
        saveType: '',
        effect: 'Hidden in roots of the tree.',
      },
    ],
    notes: '',
    stats: {
      ac: '5',
      thac0: '18',
      hd_dice: '2',
      hd_mod: '0',

      mv_land: '120',
      sv_d: '10',
      sv_w: '11',
      sv_p: '12',
      sv_b: '13',
      sv_s: '14',
      ml: '6',
      al: 'Neutral',
      xp: '25',
      na_dungeon_count: '0',
      na_dungeon_die: 'd1',
      na_wilderness_count: '1',
      na_wilderness_die: 'd6',
    },
    mvOther: [],
    treasureTypes: [
      {
        id: 'ose-monster-dryad-tt-d',
        code: 'D',
        treasureTableId: 'ose-tt-d',
        notes: '',
      },
    ],
  },
  {
    id: 'ose-monster-stirge',
    rulesetId: 'ose',
    name: 'Stirge',
    shortDescription: 'Feathered, bird-like creatures with long, sharp beaks.',
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-stirge-proboscis',
        count: '1',
        attackClass: 'melee',
        attackType: 'bite',
        customAttackType: '',
        damageDiceCount: '1',
        damageDie: 'd3',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [
          {
            id: 'ose-monster-stirge-proboscis-attach',
            effectClass: 'effect',
            effectType: 'custom',
            customType: 'Attach',
            notes: 'On hit, attaches to victim and begins draining blood.',
          },
        ],
        notes: 'Proboscis. +2 to hit on first attack. On hit, attaches and drains blood.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-stirge-blood-sucking',
        name: 'Blood sucking',
        trigger: '',
        saveType: '',
        effect: 'Upon a successful attack, attaches and drains blood: 1d3 automatic damage per round.',
      },
      {
        id: 'ose-monster-stirge-detach',
        name: 'Detach',
        trigger: '',
        saveType: '',
        effect: 'Detaches if stirge or victim dies.',
      },
    ],
    notes: '',
    stats: {
      ac: '7',
      thac0: '19',
      hd_dice: '1',
      hd_mod: '0',

      mv_land: '30',
      sv_d: '12',
      sv_w: '13',
      sv_p: '14',
      sv_b: '15',
      sv_s: '16',
      ml: '9',
      al: 'Neutral',
      xp: '13',
      na_dungeon_count: '1',
      na_dungeon_die: 'd10',
      na_wilderness_count: '3',
      na_wilderness_die: 'd12',
    },
    mvOther: [
      {
        id: 'ose-monster-stirge-fly',
        type: 'fly',
        speed: '180',
      },
    ],
    treasureTypes: [
      {
        id: 'ose-monster-stirge-tt-l',
        code: 'L',
        treasureTableId: 'ose-tt-l',
        notes: '',
      },
    ],
  },
  {
    id: 'ose-monster-sprite',
    rulesetId: 'ose',
    name: 'Sprite',
    shortDescription: "1' tall, winged humanoids, related to pixies and elves. Shy, but driven by curiosity and their odd sense of humour.",
    immunities: [],
    attacks: [
      {
        id: 'ose-monster-sprite-curse',
        count: '1',
        attackClass: 'spell',
        attackType: 'spell_like',
        customAttackType: '',
        damageDiceCount: '',
        damageDie: '',
        customDamageDie: '',
        attackBonus: '',
        onHitEffects: [
          {
            id: 'ose-monster-sprite-curse-effect',
            effectClass: 'save',
            effectType: 'spells',
            customType: '',
            notes: 'Save vs spells. Effect determined by referee, always comical (e.g. target trips, nose grows).',
          },
        ],
        notes: 'Curse. Requires 5 sprites acting collectively. No attack roll.',
      },
    ],
    traits: [
      {
        id: 'ose-monster-sprite-collective-curse',
        name: 'Collective curse',
        trigger: '',
        saveType: 'spells',
        effect: 'Five sprites can collectively curse a target (no attack roll; save vs spells). The effect is determined by the referee, but always used to comical effect.',
      },
      {
        id: 'ose-monster-sprite-pranksters',
        name: 'Pranksters',
        trigger: '',
        saveType: '',
        effect: 'Even if attacked, sprites have no interest in killing, merely in making practical jokes.',
      },
    ],
    notes: '',
    stats: {
      ac: '5',
      thac0: '19',
      hd_dice: '0.5',
      hd_mod: '0',

      mv_land: '60',
      sv_d: '12',
      sv_w: '13',
      sv_p: '13',
      sv_b: '15',
      sv_s: '15',
      ml: '7',
      al: 'Neutral',
      xp: '6',
      na_dungeon_count: '3',
      na_dungeon_die: 'd6',
      na_wilderness_count: '5',
      na_wilderness_die: 'd8',
    },
    mvOther: [
      {
        id: 'ose-monster-sprite-fly',
        type: 'fly',
        speed: '180',
      },
    ],
    treasureTypes: [
      {
        id: 'ose-monster-sprite-tt-s',
        code: 'S',
        treasureTableId: 'ose-tt-s',
        notes: '',
      },
    ],
  },
]
