import type { OseMagicArmourTable } from './types'

export const OSE_MAGIC_ARMOUR_TABLE: OseMagicArmourTable = {
  id: 'ose-magic-armour',
  name: 'Magic Armour and Shields',
  sourceUrl: 'https://oldschoolessentials.necroticgnome.com/srd/index.php/Armour_and_Shields',
  usage: 'Per normal class restrictions.',
  notes: [
    "AC penalty: Some types of cursed armour specify an Armour Class penalty. This modifier worsens the wearer's Armour Class score.",
    "AC 9 [10]: Some types of cursed armour give the wearer a base Armour Class of 9 [10] (before modifiers due to Dexterity).",
    "Testing: All types of tests indicate that a cursed shield or suit of armour is enchanted with a +1 bonus. It is only when the armour is used in deadly combat that the curse is revealed.",
    'Removing: Once a cursed shield or suit of armour has been used, the character comes under the curse and is not able to discard the item. It can only be removed with magic.',
    "Enchanted armour and shields specify a protective bonus that improves the wearer's Armour Class score.",
    "Weight: If using detailed encumbrance, enchanted armour's encumbrance value is 50% less than that of normal armour.",
  ],
  rows: [
    { basicRoll: 1, expertRoll: { min: 1, max: 15 }, resultKind: 'armour', name: 'Armour +1', rawText: 'Armour +1', bonus: 1 },
    { basicRoll: 2, expertRoll: { min: 16, max: 25 }, resultKind: 'armour-and-shield', name: 'Armour +1, Shield +1', rawText: 'Armour +1, Shield +1', bonus: 1, shieldBonus: 1 },
    { basicRoll: null, expertRoll: { min: 26, max: 27 }, resultKind: 'armour-and-shield', name: 'Armour +1, Shield +2', rawText: 'Armour +1, Shield +2', bonus: 1, shieldBonus: 2 },
    { basicRoll: null, expertRoll: { min: 28, max: 28 }, resultKind: 'armour-and-shield', name: 'Armour +1, Shield +3', rawText: 'Armour +1, Shield +3', bonus: 1, shieldBonus: 3 },
    { basicRoll: null, expertRoll: { min: 29, max: 33 }, resultKind: 'armour', name: 'Armour +2', rawText: 'Armour +2', bonus: 2 },
    { basicRoll: null, expertRoll: { min: 34, max: 36 }, resultKind: 'armour-and-shield', name: 'Armour +2, Shield +1', rawText: 'Armour +2, Shield +1', bonus: 2, shieldBonus: 1 },
    { basicRoll: null, expertRoll: { min: 37, max: 41 }, resultKind: 'armour-and-shield', name: 'Armour +2, Shield +2', rawText: 'Armour +2, Shield +2', bonus: 2, shieldBonus: 2 },
    { basicRoll: null, expertRoll: { min: 42, max: 42 }, resultKind: 'armour-and-shield', name: 'Armour +2, Shield +3', rawText: 'Armour +2, Shield +3', bonus: 2, shieldBonus: 3 },
    { basicRoll: null, expertRoll: { min: 43, max: 45 }, resultKind: 'armour', name: 'Armour +3', rawText: 'Armour +3', bonus: 3 },
    { basicRoll: null, expertRoll: { min: 46, max: 46 }, resultKind: 'armour-and-shield', name: 'Armour +3, Shield +1', rawText: 'Armour +3, Shield +1', bonus: 3, shieldBonus: 1 },
    { basicRoll: null, expertRoll: { min: 47, max: 47 }, resultKind: 'armour-and-shield', name: 'Armour +3, Shield +2', rawText: 'Armour +3, Shield +2', bonus: 3, shieldBonus: 2 },
    { basicRoll: null, expertRoll: { min: 48, max: 48 }, resultKind: 'armour-and-shield', name: 'Armour +3, Shield +3', rawText: 'Armour +3, Shield +3', bonus: 3, shieldBonus: 3 },
    { basicRoll: null, expertRoll: { min: 49, max: 51 }, resultKind: 'armour', name: 'Cursed Armour -1', rawText: 'Cursed Armour -1', bonus: -1, cursed: true },
    { basicRoll: null, expertRoll: { min: 52, max: 53 }, resultKind: 'armour', name: 'Cursed Armour -2', rawText: 'Cursed Armour -2', bonus: -2, cursed: true },
    { basicRoll: null, expertRoll: { min: 54, max: 54 }, resultKind: 'armour-and-shield', name: 'Cursed Armour -2 with Shield +1', rawText: 'Cursed Armour -2 with Shield +1', bonus: -2, shieldBonus: 1, cursed: true },
    { basicRoll: 3, expertRoll: { min: 55, max: 56 }, resultKind: 'armour', name: 'Cursed Armour, AC 9 [10]', rawText: 'Cursed Armour, AC 9 [10]', cursed: true, baseAcOverride: '9 [10]' },
    { basicRoll: null, expertRoll: { min: 57, max: 62 }, resultKind: 'shield', name: 'Cursed Shield -2', rawText: 'Cursed Shield -2', shieldBonus: -2, cursed: true },
    { basicRoll: null, expertRoll: { min: 63, max: 65 }, resultKind: 'shield', name: 'Cursed Shield, AC 9 [10]', rawText: 'Cursed Shield, AC 9 [10]', cursed: true, baseAcOverride: '9 [10]' },
    { basicRoll: 4, expertRoll: { min: 66, max: 85 }, resultKind: 'shield', name: 'Shield +1', rawText: 'Shield +1', shieldBonus: 1 },
    { basicRoll: null, expertRoll: { min: 86, max: 95 }, resultKind: 'shield', name: 'Shield +2', rawText: 'Shield +2', shieldBonus: 2 },
    { basicRoll: null, expertRoll: { min: 96, max: 100 }, resultKind: 'shield', name: 'Shield +3', rawText: 'Shield +3', shieldBonus: 3 },
  ],
  armourTypeTable: [
    { range: { min: 1, max: 2 }, armourType: 'Leather' },
    { range: { min: 3, max: 6 }, armourType: 'Chainmail' },
    { range: { min: 7, max: 8 }, armourType: 'Plate mail' },
  ],
}
