import type { OseMagicCategoryTable } from './types'

export const OSE_MAGIC_RODS_STAVES_WANDS_TABLE: OseMagicCategoryTable = {
  id: 'ose-magic-rods-staves-wands',
  name: 'Magic Rods, Staves, and Wands',
  sourceUrl: 'https://oldschoolessentials.necroticgnome.com/srd/index.php/Rods,_Staves,_Wands',
  usage: 'Varies by item type: rods are generally for all characters, staves for spell casters, and wands for arcane spell casters.',
  notes: [
    'Charges: Rods, staves, and wands have a limited number of uses called charges.',
    'The number of charges when discovered is determined by the referee and cannot be discovered by characters.',
    'Each use takes one round and consumes one charge.',
    'Consuming the last charge removes the item’s magical potency.',
    'Recharging is not possible.',
    "Rods: Usage all characters (unless noted), dimensions thin and 3' long, and unless noted contain 1d10 charges when found.",
    "Staves: Usage spell casters, some restricted to arcane or divine users, dimensions 2\" thick and 6' long, and unless noted contain 3d10 charges when found.",
    'Staves in melee: magic-users may use the staff of power, staff of striking, and staff of wizardry in melee.',
    "Wands: Usage arcane spell casters, dimensions thin and 1 1/2' long, and unless noted contain 2d10 charges when found.",
  ],
  rows: [
    { basicRoll: 1, expertRoll: { min: 1, max: 8 }, name: 'Rod of Cancellation', rawText: 'Rod of Cancellation' },
    { basicRoll: null, expertRoll: { min: 9, max: 11 }, name: 'Staff of Commanding', rawText: 'Staff of Commanding' },
    { basicRoll: 2, expertRoll: { min: 12, max: 21 }, name: 'Staff of Healing', rawText: 'Staff of Healing' },
    { basicRoll: null, expertRoll: { min: 22, max: 23 }, name: 'Staff of Power', rawText: 'Staff of Power' },
    { basicRoll: 3, expertRoll: { min: 24, max: 28 }, name: 'Staff of Snakes', rawText: 'Staff of Snakes' },
    { basicRoll: null, expertRoll: { min: 29, max: 31 }, name: 'Staff of Striking', rawText: 'Staff of Striking' },
    { basicRoll: null, expertRoll: { min: 32, max: 34 }, name: 'Staff of Withering', rawText: 'Staff of Withering' },
    { basicRoll: null, expertRoll: { min: 35, max: 35 }, name: 'Staff of Wizardry', rawText: 'Staff of Wizardry' },
    { basicRoll: null, expertRoll: { min: 36, max: 40 }, name: 'Wand of Cold', rawText: 'Wand of Cold' },
    { basicRoll: 4, expertRoll: { min: 41, max: 45 }, name: 'Wand of Enemy Detection', rawText: 'Wand of Enemy Detection' },
    { basicRoll: null, expertRoll: { min: 46, max: 50 }, name: 'Wand of Fear', rawText: 'Wand of Fear' },
    { basicRoll: null, expertRoll: { min: 51, max: 55 }, name: 'Wand of Fire Balls', rawText: 'Wand of Fire Balls' },
    { basicRoll: null, expertRoll: { min: 56, max: 60 }, name: 'Wand of Illusion', rawText: 'Wand of Illusion' },
    { basicRoll: null, expertRoll: { min: 61, max: 65 }, name: 'Wand of Lightning Bolts', rawText: 'Wand of Lightning Bolts' },
    { basicRoll: 5, expertRoll: { min: 66, max: 70 }, name: 'Wand of Magic Detection', rawText: 'Wand of Magic Detection' },
    { basicRoll: null, expertRoll: { min: 71, max: 75 }, name: 'Wand of Metal Detection', rawText: 'Wand of Metal Detection' },
    { basicRoll: null, expertRoll: { min: 76, max: 80 }, name: 'Wand of Negation', rawText: 'Wand of Negation' },
    { basicRoll: 6, expertRoll: { min: 81, max: 85 }, name: 'Wand of Paralysation', rawText: 'Wand of Paralysation' },
    { basicRoll: null, expertRoll: { min: 86, max: 90 }, name: 'Wand of Polymorph', rawText: 'Wand of Polymorph' },
    { basicRoll: null, expertRoll: { min: 91, max: 95 }, name: 'Wand of Secret Door Detection', rawText: 'Wand of Secret Door Detection' },
    { basicRoll: null, expertRoll: { min: 96, max: 100 }, name: 'Wand of Trap Detection', rawText: 'Wand of Trap Detection' },
  ],
}
