import type { OseMagicCategoryTable } from './types'

export const OSE_MAGIC_MISC_TABLE: OseMagicCategoryTable = {
  id: 'ose-magic-misc',
  name: 'Miscellaneous Magic Items',
  sourceUrl: 'https://oldschoolessentials.necroticgnome.com/srd/index.php/Miscellaneous_Items',
  usage: 'All characters (unless noted).',
  notes: [
    "Activating: Unless an item's description states otherwise, it may be used any number of times per day and is activated by concentration.",
  ],
  rows: [
    { basicRoll: null, expertRoll: { min: 1, max: 3 }, name: 'Amulet of Protection Against Scrying', rawText: 'Amulet of Protection Against Scrying' },
    { basicRoll: 1, expertRoll: { min: 4, max: 5 }, name: 'Bag of Devouring', rawText: 'Bag of Devouring' },
    { basicRoll: 2, expertRoll: { min: 6, max: 11 }, name: 'Bag of Holding', rawText: 'Bag of Holding' },
    { basicRoll: null, expertRoll: { min: 12, max: 16 }, name: 'Boots of Levitation', rawText: 'Boots of Levitation' },
    { basicRoll: null, expertRoll: { min: 17, max: 21 }, name: 'Boots of Speed', rawText: 'Boots of Speed' },
    { basicRoll: null, expertRoll: { min: 22, max: 26 }, name: 'Boots of Travelling and Leaping', rawText: 'Boots of Travelling and Leaping' },
    { basicRoll: 3, expertRoll: { min: 27, max: 31 }, name: 'Broom of Flying', rawText: 'Broom of Flying' },
    { basicRoll: 4, expertRoll: { min: 32, max: 35 }, name: 'Crystal Ball', rawText: 'Crystal Ball' },
    {
      basicRoll: null,
      expertRoll: { min: 36, max: 37 },
      name: 'Crystal Ball with Clairaudience',
      rawText: 'Crystal Ball with Clairaudience',
      variant: 'Clairaudience',
    },
    {
      basicRoll: null,
      expertRoll: { min: 38, max: 38 },
      name: 'Crystal Ball with ESP',
      rawText: 'Crystal Ball with ESP',
      variant: 'ESP',
    },
    { basicRoll: null, expertRoll: { min: 39, max: 40 }, name: 'Displacer Cloak', rawText: 'Displacer Cloak' },
    { basicRoll: null, expertRoll: { min: 41, max: 41 }, name: 'Drums of Panic', rawText: 'Drums of Panic' },
    { basicRoll: null, expertRoll: { min: 42, max: 42 }, name: 'Efreeti Bottle', rawText: 'Efreeti Bottle' },
    { basicRoll: null, expertRoll: { min: 43, max: 43 }, name: 'Elemental Summoning Device', rawText: 'Elemental Summoning Device: Air', element: 'Air' },
    { basicRoll: null, expertRoll: { min: 44, max: 44 }, name: 'Elemental Summoning Device', rawText: 'Elemental Summoning Device: Earth', element: 'Earth' },
    { basicRoll: null, expertRoll: { min: 45, max: 45 }, name: 'Elemental Summoning Device', rawText: 'Elemental Summoning Device: Fire', element: 'Fire' },
    { basicRoll: null, expertRoll: { min: 46, max: 46 }, name: 'Elemental Summoning Device', rawText: 'Elemental Summoning Device: Water', element: 'Water' },
    { basicRoll: 5, expertRoll: { min: 47, max: 56 }, name: 'Elven Cloak and Boots', rawText: 'Elven Cloak and Boots' },
    { basicRoll: null, expertRoll: { min: 57, max: 57 }, name: 'Flying Carpet', rawText: 'Flying Carpet' },
    { basicRoll: 6, expertRoll: { min: 58, max: 64 }, name: 'Gauntlets of Ogre Power', rawText: 'Gauntlets of Ogre Power' },
    { basicRoll: null, expertRoll: { min: 65, max: 66 }, name: 'Girdle of Giant Strength', rawText: 'Girdle of Giant Strength' },
    { basicRoll: 7, expertRoll: { min: 67, max: 77 }, name: 'Helm of Alignment Changing', rawText: 'Helm of Alignment Changing' },
    { basicRoll: null, expertRoll: { min: 78, max: 82 }, name: 'Helm of Reading Languages and Magic', rawText: 'Helm of Reading Languages and Magic' },
    { basicRoll: 8, expertRoll: { min: 83, max: 83 }, name: 'Helm of Telepathy', rawText: 'Helm of Telepathy' },
    { basicRoll: null, expertRoll: { min: 84, max: 84 }, name: 'Helm of Teleportation', rawText: 'Helm of Teleportation' },
    { basicRoll: null, expertRoll: { min: 85, max: 85 }, name: 'Horn of Blasting', rawText: 'Horn of Blasting' },
    { basicRoll: 9, expertRoll: { min: 86, max: 90 }, name: 'Medallion of ESP', rawText: 'Medallion of ESP 30’', rangeText: "30'" },
    { basicRoll: null, expertRoll: { min: 91, max: 93 }, name: 'Medallion of ESP', rawText: 'Medallion of ESP 90’', rangeText: "90'" },
    { basicRoll: null, expertRoll: { min: 94, max: 94 }, name: 'Mirror of Life Trapping', rawText: 'Mirror of Life Trapping' },
    { basicRoll: 10, expertRoll: { min: 95, max: 97 }, name: 'Rope of Climbing', rawText: 'Rope of Climbing' },
    { basicRoll: null, expertRoll: { min: 98, max: 100 }, name: 'Scarab of Protection', rawText: 'Scarab of Protection' },
  ],
}
