import type { OseMagicScrollsMapsTable } from './types'

export const OSE_MAGIC_SCROLLS_MAPS_TABLE: OseMagicScrollsMapsTable = {
  id: 'ose-magic-scrolls-maps',
  name: 'Magic Scrolls and Maps',
  sourceUrl: 'https://oldschoolessentials.necroticgnome.com/srd/index.php/Scrolls_and_Maps',
  usage: 'Varies by scroll type; treasure maps are usable by all characters.',
  notes: [
    'Scrolls are aged sheets of parchment or paper on which magical words have been written by a high-level spell caster.',
    'One use only: When a scroll is read, the words disappear.',
    'A scroll can only be used if there is enough light to read by.',
  ],
  cursedScrollNotes: [
    'Usage: All characters (unless noted).',
    'Activation: Merely looking at the baneful script on the scroll curses the character.',
    'Removing: A curse can be removed by magic, or at the referee’s option, by performing a special quest.',
    'Example curses include transformation, summoning, lost item, energy drain, ability score re-roll, and slow healing.',
  ],
  protectionScrollNotes: [
    'Usage: All characters (unless noted). Written in non-magical languages, usually Common.',
    'Activation: Reading the script aloud conjures a 10’ radius circle of protection around the reader.',
    'The circle follows the reader if they move.',
    'Protection from Elementals: Duration 2 turns unless broken; ranged attacks still work; melee attacks from inside the circle break it.',
    'Protection from Lycanthropes: Duration 6 turns unless broken; number affected depends on HD.',
    'Protection from Magic: Blocks spells and spell-like effects in both directions; duration 1d4 turns; only a wish can dispel it.',
    'Protection from Undead: Duration 6 turns unless broken; number affected depends on HD.',
  ],
  spellScrollNotes: [
    'Usage: Spell casters.',
    'Type of magic: 1-in-4 scrolls contain divine spells; the rest contain arcane spells.',
    'Activation: Reading the script aloud conjures the effect of a specific spell.',
    'Only arcane spell casters can use arcane scrolls. Only divine spell casters can use divine scrolls.',
    'If a scroll contains multiple spells, only the spell cast disappears from the scroll.',
    'The referee may choose spells or roll randomly for spell level using the Random Scroll Spell Level table.',
  ],
  treasureMapNotes: [
    'Usage: All characters (unless noted).',
    'A treasure map indicates the route to a valuable treasure in a dungeon or wilderness.',
    'Maps may be incomplete, written as riddles, or in obscure languages.',
    'The referee should prepare treasure maps in advance.',
    'For hoards with a listed GP value, the referee may choose the treasure composition.',
    'Treasure is normally guarded by enchantments, traps, or monsters.',
  ],
  mainRows: [
    { basicRoll: 1, expertRoll: { min: 1, max: 15 }, name: '1 Spell', rawText: '1 Spell' },
    { basicRoll: 2, expertRoll: { min: 16, max: 25 }, name: '2 Spells', rawText: '2 Spells' },
    { basicRoll: 3, expertRoll: { min: 26, max: 31 }, name: '3 Spells', rawText: '3 Spells' },
    { basicRoll: null, expertRoll: { min: 32, max: 34 }, name: '5 Spells', rawText: '5 Spells' },
    { basicRoll: null, expertRoll: { min: 35, max: 35 }, name: '7 Spells', rawText: '7 Spells' },
    { basicRoll: 4, expertRoll: { min: 36, max: 40 }, name: 'Cursed Scroll', rawText: 'Cursed Scroll', harmful: true },
    { basicRoll: null, expertRoll: { min: 41, max: 50 }, name: 'Protection from Elementals', rawText: 'Prot. from Elementals' },
    { basicRoll: 5, expertRoll: { min: 51, max: 60 }, name: 'Protection from Lycanthropes', rawText: 'Prot. from Lycanthropes' },
    { basicRoll: null, expertRoll: { min: 61, max: 65 }, name: 'Protection from Magic', rawText: 'Prot. from Magic' },
    { basicRoll: 6, expertRoll: { min: 66, max: 75 }, name: 'Protection from Undead', rawText: 'Prot. from Undead' },
    { basicRoll: 7, expertRoll: { min: 76, max: 78 }, name: 'Treasure Map: I', rawText: 'Treasure Map: I' },
    { basicRoll: null, expertRoll: { min: 79, max: 80 }, name: 'Treasure Map: II', rawText: 'Treasure Map: II' },
    { basicRoll: null, expertRoll: { min: 81, max: 82 }, name: 'Treasure Map: III', rawText: 'Treasure Map: III' },
    { basicRoll: null, expertRoll: { min: 83, max: 83 }, name: 'Treasure Map: IV', rawText: 'Treasure Map: IV' },
    { basicRoll: null, expertRoll: { min: 84, max: 84 }, name: 'Treasure Map: V', rawText: 'Treasure Map: V' },
    { basicRoll: null, expertRoll: { min: 85, max: 85 }, name: 'Treasure Map: VI', rawText: 'Treasure Map: VI' },
    { basicRoll: null, expertRoll: { min: 86, max: 86 }, name: 'Treasure Map: VII', rawText: 'Treasure Map: VII' },
    { basicRoll: 8, expertRoll: { min: 87, max: 90 }, name: 'Treasure Map: VIII', rawText: 'Treasure Map: VIII' },
    { basicRoll: null, expertRoll: { min: 91, max: 95 }, name: 'Treasure Map: IX', rawText: 'Treasure Map: IX' },
    { basicRoll: null, expertRoll: { min: 96, max: 96 }, name: 'Treasure Map: X', rawText: 'Treasure Map: X' },
    { basicRoll: null, expertRoll: { min: 97, max: 98 }, name: 'Treasure Map: XI', rawText: 'Treasure Map: XI' },
    { basicRoll: null, expertRoll: { min: 99, max: 100 }, name: 'Treasure Map: XII', rawText: 'Treasure Map: XII' },
  ],
  randomSpellLevelRows: [
    { basicRoll: { min: 1, max: 3 }, expertRoll: { min: 1, max: 25 }, arcaneLevel: 1, divineLevel: 1 },
    { basicRoll: { min: 4, max: 5 }, expertRoll: { min: 26, max: 50 }, arcaneLevel: 2, divineLevel: 2 },
    { basicRoll: { min: 6, max: 6 }, expertRoll: { min: 51, max: 70 }, arcaneLevel: 3, divineLevel: 3 },
    { basicRoll: null, expertRoll: { min: 71, max: 85 }, arcaneLevel: 4, divineLevel: 4 },
    { basicRoll: null, expertRoll: { min: 86, max: 95 }, arcaneLevel: 5, divineLevel: 5 },
    { basicRoll: null, expertRoll: { min: 96, max: 100 }, arcaneLevel: 6, divineLevel: 5 },
  ],
  treasureMapRows: [
    { mapCode: 'I', result: '1 magic item.' },
    { mapCode: 'II', result: '1d6 x 10 gems and 2d10 pieces of jewellery.' },
    { mapCode: 'III', result: '2 magic items.' },
    { mapCode: 'IV', result: '3 magic items (no swords).' },
    { mapCode: 'V', result: '3 magic items and 1 potion.' },
    { mapCode: 'VI', result: '3 magic items, 1 scroll, 1 potion.' },
    { mapCode: 'VII', result: '5d6 gems and 2 magic items.' },
    { mapCode: 'VIII', result: 'Hoard worth 1d4 x 1,000gp.' },
    { mapCode: 'IX', result: 'Hoard worth 5d6 x 1,000gp.' },
    { mapCode: 'X', result: 'Hoard worth 5d6 x 1,000gp and 1 magic item.' },
    { mapCode: 'XI', result: 'Hoard worth 5d6 x 1,000gp and 5d6 gems.' },
    { mapCode: 'XII', result: 'Hoard worth 6d6 x 1,000gp.' },
  ],
}
