import type { OseMagicCategoryTable } from './types'

export const OSE_MAGIC_POTIONS_TABLE: OseMagicCategoryTable = {
  id: 'ose-magic-potions',
  name: 'Magic Potions',
  sourceUrl: 'https://oldschoolessentials.necroticgnome.com/srd/index.php/Potions',
  usage: 'All characters (unless noted).',
  notes: [
    'Identifying: A potion may be identified by sipping a small amount.',
    'Drinking a full dose of a potion takes one round.',
    'Duration: The magical effect of a full dose of a potion lasts for 1d6+6 turns unless the effect is instantaneous or permanent.',
    'Mixing Potions: Drinking a potion while already under the effects of another potion is dangerous.',
    'Mixing result: The character is completely disabled for 3 turns due to sickness.',
    'Mixing result: The effects of both potions are cancelled.',
    'The mixing rule does not apply to potions with instantaneous or permanent duration.',
  ],
  rows: [
    { basicRoll: null, expertRoll: { min: 1, max: 3 }, name: 'Clairaudience', rawText: 'Clairaudience' },
    { basicRoll: null, expertRoll: { min: 4, max: 7 }, name: 'Clairvoyance', rawText: 'Clairvoyance' },
    { basicRoll: null, expertRoll: { min: 8, max: 10 }, name: 'Control Animal', rawText: 'Control Animal' },
    { basicRoll: null, expertRoll: { min: 11, max: 13 }, name: 'Control Dragon', rawText: 'Control Dragon' },
    { basicRoll: null, expertRoll: { min: 14, max: 16 }, name: 'Control Giant', rawText: 'Control Giant' },
    { basicRoll: null, expertRoll: { min: 17, max: 19 }, name: 'Control Human', rawText: 'Control Human' },
    { basicRoll: null, expertRoll: { min: 20, max: 22 }, name: 'Control Plant', rawText: 'Control Plant' },
    { basicRoll: null, expertRoll: { min: 23, max: 25 }, name: 'Control Undead', rawText: 'Control Undead' },
    { basicRoll: null, expertRoll: { min: 26, max: 32 }, name: 'Delusion', rawText: 'Delusion' },
    { basicRoll: 1, expertRoll: { min: 33, max: 35 }, name: 'Diminution', rawText: 'Diminution' },
    { basicRoll: 2, expertRoll: { min: 36, max: 39 }, name: 'ESP', rawText: 'ESP' },
    { basicRoll: null, expertRoll: { min: 40, max: 43 }, name: 'Fire Resistance', rawText: 'Fire Resistance' },
    { basicRoll: null, expertRoll: { min: 44, max: 47 }, name: 'Flying', rawText: 'Flying' },
    { basicRoll: 3, expertRoll: { min: 48, max: 51 }, name: 'Gaseous Form', rawText: 'Gaseous Form' },
    { basicRoll: null, expertRoll: { min: 52, max: 55 }, name: 'Giant Strength', rawText: 'Giant Strength' },
    { basicRoll: 4, expertRoll: { min: 56, max: 59 }, name: 'Growth', rawText: 'Growth' },
    { basicRoll: 5, expertRoll: { min: 60, max: 63 }, name: 'Healing', rawText: 'Healing' },
    { basicRoll: null, expertRoll: { min: 64, max: 68 }, name: 'Heroism', rawText: 'Heroism' },
    { basicRoll: 6, expertRoll: { min: 69, max: 72 }, name: 'Invisibility', rawText: 'Invisibility' },
    { basicRoll: null, expertRoll: { min: 73, max: 76 }, name: 'Invulnerability', rawText: 'Invulnerability' },
    { basicRoll: 7, expertRoll: { min: 77, max: 80 }, name: 'Levitation', rawText: 'Levitation' },
    { basicRoll: null, expertRoll: { min: 81, max: 84 }, name: 'Longevity', rawText: 'Longevity' },
    { basicRoll: 8, expertRoll: { min: 85, max: 86 }, name: 'Poison', rawText: 'Poison', harmful: true },
    { basicRoll: null, expertRoll: { min: 87, max: 89 }, name: 'Polymorph Self', rawText: 'Polymorph Self' },
    { basicRoll: null, expertRoll: { min: 90, max: 97 }, name: 'Speed', rawText: 'Speed' },
    { basicRoll: null, expertRoll: { min: 98, max: 100 }, name: 'Treasure Finding', rawText: 'Treasure Finding' },
  ],
}
